INSERT INTO dim_team (team_id, name, abbreviation, team_name, location_name, first_year_of_play, short_name, official_site_url, franchise_id, active, venue_name, venue_city, venue_id, venue_time_zone_id, venue_time_zone_offset, venue_time_zone_tz, division_id, division_name, division_name_short, division_abbreviation, conference_id, conference_name, franchise_franchise_id, franchise_team_name) 
VALUES ('1', 'New Jersey Devils', 'NJD', 'Devils', 'New Jersey', 1982, 'New Jersey', 'http://www.newjerseydevils.com/', '23', 'TRUE', 'Prudential Center', 'Newark', NULL, 'America/New_York', -4, 'EDT', '18', 'Metropolitan', 'Metro', 'M', '6', 'Eastern', '23', 'Devils');

INSERT INTO dim_team (team_id, name, abbreviation, team_name, location_name, first_year_of_play, short_name, official_site_url, franchise_id, active, venue_name, venue_city, venue_id, venue_time_zone_id, venue_time_zone_offset, venue_time_zone_tz, division_id, division_name, division_name_short, division_abbreviation, conference_id, conference_name, franchise_franchise_id, franchise_team_name) 
VALUES ('2', 'New York Islanders', 'NYI', 'Islanders', 'New York', 1972, 'NY Islanders', 'http://www.newyorkislanders.com/', '22', 'TRUE', 'UBS Arena', 'Elmont', NULL, 'America/New_York', -4, 'EDT', '18', 'Metropolitan', 'Metro', 'M', '6', 'Eastern', '22', 'Islanders');

INSERT INTO dim_team (team_id, name, abbreviation, team_name, location_name, first_year_of_play, short_name, official_site_url, franchise_id, active, venue_name, venue_city, venue_id, venue_time_zone_id, venue_time_zone_offset, venue_time_zone_tz, division_id, division_name, division_name_short, division_abbreviation, conference_id, conference_name, franchise_franchise_id, franchise_team_name) 
VALUES ('3', 'New York Rangers', 'NYR', 'Rangers', 'New York', 1926, 'NY Rangers', 'http://www.newyorkrangers.com/', '10', 'TRUE', 'Madison Square Garden', 'New York', 5054, 'America/New_York', -4, 'EDT', '18', 'Metropolitan', 'Metro', 'M', '6', 'Eastern', '10', 'Rangers');

INSERT INTO dim_team (team_id, name, abbreviation, team_name, location_name, first_year_of_play, short_name, official_site_url, franchise_id, active, venue_name, venue_city, venue_id, venue_time_zone_id, venue_time_zone_offset, venue_time_zone_tz, division_id, division_name, division_name_short, division_abbreviation, conference_id, conference_name, franchise_franchise_id, franchise_team_name) 
VALUES ('4', 'Philadelphia Flyers', 'PHI', 'Flyers', 'Philadelphia', 1967, 'Philadelphia', 'http://www.philadelphiaflyers.com/', '16', 'TRUE', 'Wells Fargo Center', 'Philadelphia', 5096, 'America/New_York', -4, 'EDT', '18', 'Metropolitan', 'Metro', 'M', '6', 'Eastern', '16', 'Flyers');

INSERT INTO dim_team (team_id, name, abbreviation, team_name, location_name, first_year_of_play, short_name, official_site_url, franchise_id, active, venue_name, venue_city, venue_id, venue_time_zone_id, venue_time_zone_offset, venue_time_zone_tz, division_id, division_name, division_name_short, division_abbreviation, conference_id, conference_name, franchise_franchise_id, franchise_team_name) 
VALUES ('5', 'Pittsburgh Penguins', 'PIT', 'Penguins', 'Pittsburgh', 1967, 'Pittsburgh', 'http://pittsburghpenguins.com/', '17', 'TRUE', 'PPG Paints Arena', 'Pittsburgh', 5034, 'America/New_York', -4, 'EDT', '18', 'Metropolitan', 'Metro', 'M', '6', 'Eastern', '17', 'Penguins');

INSERT INTO dim_team (team_id, name, abbreviation, team_name, location_name, first_year_of_play, short_name, official_site_url, franchise_id, active, venue_name, venue_city, venue_id, venue_time_zone_id, venue_time_zone_offset, venue_time_zone_tz, division_id, division_name, division_name_short, division_abbreviation, conference_id, conference_name, franchise_franchise_id, franchise_team_name) 
VALUES ('6', 'Boston Bruins', 'BOS', 'Bruins', 'Boston', 1924, 'Boston', 'http://www.bostonbruins.com/', '6', 'TRUE', 'TD Garden', 'Boston', 5085, 'America/New_York', -4, 'EDT', '17', 'Atlantic', 'ATL', 'A', '6', 'Eastern', '6', 'Bruins');

INSERT INTO dim_team (team_id, name, abbreviation, team_name, location_name, first_year_of_play, short_name, official_site_url, franchise_id, active, venue_name, venue_city, venue_id, venue_time_zone_id, venue_time_zone_offset, venue_time_zone_tz, division_id, division_name, division_name_short, division_abbreviation, conference_id, conference_name, franchise_franchise_id, franchise_team_name) 
VALUES ('7', 'Buffalo Sabres', 'BUF', 'Sabres', 'Buffalo', 1970, 'Buffalo', 'http://www.sabres.com/', '19', 'TRUE', 'KeyBank Center', 'Buffalo', 5039, 'America/New_York', -4, 'EDT', '17', 'Atlantic', 'ATL', 'A', '6', 'Eastern', '19', 'Sabres');

INSERT INTO dim_team (team_id, name, abbreviation, team_name, location_name, first_year_of_play, short_name, official_site_url, franchise_id, active, venue_name, venue_city, venue_id, venue_time_zone_id, venue_time_zone_offset, venue_time_zone_tz, division_id, division_name, division_name_short, division_abbreviation, conference_id, conference_name, franchise_franchise_id, franchise_team_name) 
VALUES ('8', 'Montreal Canadiens', 'MTL', 'Canadiens', 'Montreal', 1909, 'Montreal', 'http://www.canadiens.com/', '1', 'TRUE', 'Bell Centre', 'Montreal', 5028, 'America/Montreal', -4, 'EDT', '17', 'Atlantic', 'ATL', 'A', '6', 'Eastern', '1', 'Canadiens');

INSERT INTO dim_team (team_id, name, abbreviation, team_name, location_name, first_year_of_play, short_name, official_site_url, franchise_id, active, venue_name, venue_city, venue_id, venue_time_zone_id, venue_time_zone_offset, venue_time_zone_tz, division_id, division_name, division_name_short, division_abbreviation, conference_id, conference_name, franchise_franchise_id, franchise_team_name) 
VALUES ('9', 'Ottawa Senators', 'OTT', 'Senators', 'Ottawa', 1990, 'Ottawa', 'http://www.ottawasenators.com/', '30', 'TRUE', 'Canadian Tire Centre', 'Ottawa', 5031, 'America/New_York', -4, 'EDT', '17', 'Atlantic', 'ATL', 'A', '6', 'Eastern', '30', 'Senators');

INSERT INTO dim_team (team_id, name, abbreviation, team_name, location_name, first_year_of_play, short_name, official_site_url, franchise_id, active, venue_name, venue_city, venue_id, venue_time_zone_id, venue_time_zone_offset, venue_time_zone_tz, division_id, division_name, division_name_short, division_abbreviation, conference_id, conference_name, franchise_franchise_id, franchise_team_name) 
VALUES ('10', 'Toronto Maple Leafs', 'TOR', 'Maple Leafs', 'Toronto', 1917, 'Toronto', 'http://www.mapleleafs.com/', '5', 'TRUE', 'Scotiabank Arena', 'Toronto', NULL, 'America/Toronto', -4, 'EDT', '17', 'Atlantic', 'ATL', 'A', '6', 'Eastern', '5', 'Maple Leafs');

INSERT INTO dim_team (team_id, name, abbreviation, team_name, location_name, first_year_of_play, short_name, official_site_url, franchise_id, active, venue_name, venue_city, venue_id, venue_time_zone_id, venue_time_zone_offset, venue_time_zone_tz, division_id, division_name, division_name_short, division_abbreviation, conference_id, conference_name, franchise_franchise_id, franchise_team_name) 
VALUES ('12', 'Carolina Hurricanes', 'CAR', 'Hurricanes', 'Carolina', 1979, 'Carolina', 'http://www.carolinahurricanes.com/', '26', 'TRUE', 'PNC Arena', 'Raleigh', 5066, 'America/New_York', -4, 'EDT', '18', 'Metropolitan', 'Metro', 'M', '6', 'Eastern', '26', 'Hurricanes');

INSERT INTO dim_team (team_id, name, abbreviation, team_name, location_name, first_year_of_play, short_name, official_site_url, franchise_id, active, venue_name, venue_city, venue_id, venue_time_zone_id, venue_time_zone_offset, venue_time_zone_tz, division_id, division_name, division_name_short, division_abbreviation, conference_id, conference_name, franchise_franchise_id, franchise_team_name) 
VALUES ('13', 'Florida Panthers', 'FLA', 'Panthers', 'Florida', 1993, 'Florida', 'http://www.floridapanthers.com/', '33', 'TRUE', 'FLA Live Arena', 'Sunrise', 5027, 'America/New_York', -4, 'EDT', '17', 'Atlantic', 'ATL', 'A', '6', 'Eastern', '33', 'Panthers');

INSERT INTO dim_team (team_id, name, abbreviation, team_name, location_name, first_year_of_play, short_name, official_site_url, franchise_id, active, venue_name, venue_city, venue_id, venue_time_zone_id, venue_time_zone_offset, venue_time_zone_tz, division_id, division_name, division_name_short, division_abbreviation, conference_id, conference_name, franchise_franchise_id, franchise_team_name) 
VALUES ('14', 'Tampa Bay Lightning', 'TBL', 'Lightning', 'Tampa Bay', 1991, 'Tampa Bay', 'http://www.tampabaylightning.com/', '31', 'TRUE', 'AMALIE Arena', 'Tampa', NULL, 'America/New_York', -4, 'EDT', '17', 'Atlantic', 'ATL', 'A', '6', 'Eastern', '31', 'Lightning');

INSERT INTO dim_team (team_id, name, abbreviation, team_name, location_name, first_year_of_play, short_name, official_site_url, franchise_id, active, venue_name, venue_city, venue_id, venue_time_zone_id, venue_time_zone_offset, venue_time_zone_tz, division_id, division_name, division_name_short, division_abbreviation, conference_id, conference_name, franchise_franchise_id, franchise_team_name) 
VALUES ('15', 'Washington Capitals', 'WSH', 'Capitals', 'Washington', 1974, 'Washington', 'http://www.washingtoncapitals.com/', '24', 'TRUE', 'Capital One Arena', 'Washington', 5094, 'America/New_York', -4, 'EDT', '18', 'Metropolitan', 'Metro', 'M', '6', 'Eastern', '24', 'Capitals');

INSERT INTO dim_team (team_id, name, abbreviation, team_name, location_name, first_year_of_play, short_name, official_site_url, franchise_id, active, venue_name, venue_city, venue_id, venue_time_zone_id, venue_time_zone_offset, venue_time_zone_tz, division_id, division_name, division_name_short, division_abbreviation, conference_id, conference_name, franchise_franchise_id, franchise_team_name) 
VALUES ('16', 'Chicago Blackhawks', 'CHI', 'Blackhawks', 'Chicago', 1926, 'Chicago', 'http://www.chicagoblackhawks.com/', '11', 'TRUE', 'United Center', 'Chicago', 5092, 'America/Chicago', -5, 'CDT', '16', 'Central', 'CEN', 'C', '5', 'Western', '11', 'Blackhawks');

INSERT INTO dim_team (team_id, name, abbreviation, team_name, location_name, first_year_of_play, short_name, official_site_url, franchise_id, active, venue_name, venue_city, venue_id, venue_time_zone_id, venue_time_zone_offset, venue_time_zone_tz, division_id, division_name, division_name_short, division_abbreviation, conference_id, conference_name, franchise_franchise_id, franchise_team_name) 
VALUES ('17', 'Detroit Red Wings', 'DET', 'Red Wings', 'Detroit', 1926, 'Detroit', 'http://www.detroitredwings.com/', '12', 'TRUE', 'Little Caesars Arena', 'Detroit', 5145, 'America/Detroit', -4, 'EDT', '17', 'Atlantic', 'ATL', 'A', '6', 'Eastern', '12', 'Red Wings');

INSERT INTO dim_team (team_id, name, abbreviation, team_name, location_name, first_year_of_play, short_name, official_site_url, franchise_id, active, venue_name, venue_city, venue_id, venue_time_zone_id, venue_time_zone_offset, venue_time_zone_tz, division_id, division_name, division_name_short, division_abbreviation, conference_id, conference_name, franchise_franchise_id, franchise_team_name) 
VALUES ('18', 'Nashville Predators', 'NSH', 'Predators', 'Nashville', 1997, 'Nashville', 'http://www.nashvillepredators.com/', '34', 'TRUE', 'Bridgestone Arena', 'Nashville', 5030, 'America/Chicago', -5, 'CDT', '16', 'Central', 'CEN', 'C', '5', 'Western', '34', 'Predators');

INSERT INTO dim_team (team_id, name, abbreviation, team_name, location_name, first_year_of_play, short_name, official_site_url, franchise_id, active, venue_name, venue_city, venue_id, venue_time_zone_id, venue_time_zone_offset, venue_time_zone_tz, division_id, division_name, division_name_short, division_abbreviation, conference_id, conference_name, franchise_franchise_id, franchise_team_name) 
VALUES ('19', 'St. Louis Blues', 'STL', 'Blues', 'St. Louis', 1967, 'St Louis', 'http://www.stlouisblues.com/', '18', 'TRUE', 'Enterprise Center', 'St. Louis', 5076, 'America/Chicago', -5, 'CDT', '16', 'Central', 'CEN', 'C', '5', 'Western', '18', 'Blues');

INSERT INTO dim_team (team_id, name, abbreviation, team_name, location_name, first_year_of_play, short_name, official_site_url, franchise_id, active, venue_name, venue_city, venue_id, venue_time_zone_id, venue_time_zone_offset, venue_time_zone_tz, division_id, division_name, division_name_short, division_abbreviation, conference_id, conference_name, franchise_franchise_id, franchise_team_name) 
VALUES ('20', 'Calgary Flames', 'CGY', 'Flames', 'Calgary', 1980, 'Calgary', 'http://www.calgaryflames.com/', '21', 'TRUE', 'Scotiabank Saddledome', 'Calgary', 5075, 'America/Denver', -6, 'MDT', '15', 'Pacific', 'PAC', 'P', '5', 'Western', '21', 'Flames');

INSERT INTO dim_team (team_id, name, abbreviation, team_name, location_name, first_year_of_play, short_name, official_site_url, franchise_id, active, venue_name, venue_city, venue_id, venue_time_zone_id, venue_time_zone_offset, venue_time_zone_tz, division_id, division_name, division_name_short, division_abbreviation, conference_id, conference_name, franchise_franchise_id, franchise_team_name) 
VALUES ('21', 'Colorado Avalanche', 'COL', 'Avalanche', 'Colorado', 1979, 'Colorado', 'http://www.coloradoavalanche.com/', '27', 'TRUE', 'Ball Arena', 'Denver', 5064, 'America/Denver', -6, 'MDT', '16', 'Central', 'CEN', 'C', '5', 'Western', '27', 'Avalanche');

INSERT INTO dim_team (team_id, name, abbreviation, team_name, location_name, first_year_of_play, short_name, official_site_url, franchise_id, active, venue_name, venue_city, venue_id, venue_time_zone_id, venue_time_zone_offset, venue_time_zone_tz, division_id, division_name, division_name_short, division_abbreviation, conference_id, conference_name, franchise_franchise_id, franchise_team_name) 
VALUES ('22', 'Edmonton Oilers', 'EDM', 'Oilers', 'Edmonton', 1979, 'Edmonton', 'http://www.edmontonoilers.com/', '25', 'TRUE', 'Rogers Place', 'Edmonton', 5100, 'America/Edmonton', -6, 'MDT', '15', 'Pacific', 'PAC', 'P', '5', 'Western', '25', 'Oilers');

INSERT INTO dim_team (team_id, name, abbreviation, team_name, location_name, first_year_of_play, short_name, official_site_url, franchise_id, active, venue_name, venue_city, venue_id, venue_time_zone_id, venue_time_zone_offset, venue_time_zone_tz, division_id, division_name, division_name_short, division_abbreviation, conference_id, conference_name, franchise_franchise_id, franchise_team_name) 
VALUES ('23', 'Vancouver Canucks', 'VAN', 'Canucks', 'Vancouver', 1970, 'Vancouver', 'http://www.canucks.com/', '20', 'TRUE', 'Rogers Arena', 'Vancouver', 5073, 'America/Vancouver', -7, 'PDT', '15', 'Pacific', 'PAC', 'P', '5', 'Western', '20', 'Canucks');

INSERT INTO dim_team (team_id, name, abbreviation, team_name, location_name, first_year_of_play, short_name, official_site_url, franchise_id, active, venue_name, venue_city, venue_id, venue_time_zone_id, venue_time_zone_offset, venue_time_zone_tz, division_id, division_name, division_name_short, division_abbreviation, conference_id, conference_name, franchise_franchise_id, franchise_team_name) 
VALUES ('24', 'Anaheim Ducks', 'ANA', 'Ducks', 'Anaheim', 1993, 'Anaheim', 'http://www.anaheimducks.com/', '32', 'TRUE', 'Honda Center', 'Anaheim', 5046, 'America/Los_Angeles', -7, 'PDT', '15', 'Pacific', 'PAC', 'P', '5', 'Western', '32', 'Ducks');

INSERT INTO dim_team (team_id, name, abbreviation, team_name, location_name, first_year_of_play, short_name, official_site_url, franchise_id, active, venue_name, venue_city, venue_id, venue_time_zone_id, venue_time_zone_offset, venue_time_zone_tz, division_id, division_name, division_name_short, division_abbreviation, conference_id, conference_name, franchise_franchise_id, franchise_team_name) 
VALUES ('25', 'Dallas Stars', 'DAL', 'Stars', 'Dallas', 1967, 'Dallas', 'http://www.dallasstars.com/', '15', 'TRUE', 'American Airlines Center', 'Dallas', 5019, 'America/Chicago', -5, 'CDT', '16', 'Central', 'CEN', 'C', '5', 'Western', '15', 'Stars');

INSERT INTO dim_team (team_id, name, abbreviation, team_name, location_name, first_year_of_play, short_name, official_site_url, franchise_id, active, venue_name, venue_city, venue_id, venue_time_zone_id, venue_time_zone_offset, venue_time_zone_tz, division_id, division_name, division_name_short, division_abbreviation, conference_id, conference_name, franchise_franchise_id, franchise_team_name) 
VALUES ('26', 'Los Angeles Kings', 'LAK', 'Kings', 'Los Angeles', 1967, 'Los Angeles', 'http://www.lakings.com/', '14', 'TRUE', 'Crypto.com Arena', 'Los Angeles', NULL, 'America/Los_Angeles', -7, 'PDT', '15', 'Pacific', 'PAC', 'P', '5', 'Western', '14', 'Kings');

INSERT INTO dim_team (team_id, name, abbreviation, team_name, location_name, first_year_of_play, short_name, official_site_url, franchise_id, active, venue_name, venue_city, venue_id, venue_time_zone_id, venue_time_zone_offset, venue_time_zone_tz, division_id, division_name, division_name_short, division_abbreviation, conference_id, conference_name, franchise_franchise_id, franchise_team_name) 
VALUES ('28', 'San Jose Sharks', 'SJS', 'Sharks', 'San Jose', 1990, 'San Jose', 'http://www.sjsharks.com/', '29', 'TRUE', 'SAP Center at San Jose', 'San Jose', NULL, 'America/Los_Angeles', -7, 'PDT', '15', 'Pacific', 'PAC', 'P', '5', 'Western', '29', 'Sharks');

INSERT INTO dim_team (team_id, name, abbreviation, team_name, location_name, first_year_of_play, short_name, official_site_url, franchise_id, active, venue_name, venue_city, venue_id, venue_time_zone_id, venue_time_zone_offset, venue_time_zone_tz, division_id, division_name, division_name_short, division_abbreviation, conference_id, conference_name, franchise_franchise_id, franchise_team_name) 
VALUES ('29', 'Columbus Blue Jackets', 'CBJ', 'Blue Jackets', 'Columbus', 1997, 'Columbus', 'http://www.bluejackets.com/', '36', 'TRUE', 'Nationwide Arena', 'Columbus', 5059, 'America/New_York', -4, 'EDT', '18', 'Metropolitan', 'Metro', 'M', '6', 'Eastern', '36', 'Blue Jackets');

INSERT INTO dim_team (team_id, name, abbreviation, team_name, location_name, first_year_of_play, short_name, official_site_url, franchise_id, active, venue_name, venue_city, venue_id, venue_time_zone_id, venue_time_zone_offset, venue_time_zone_tz, division_id, division_name, division_name_short, division_abbreviation, conference_id, conference_name, franchise_franchise_id, franchise_team_name) 
VALUES ('30', 'Minnesota Wild', 'MIN', 'Wild', 'Minnesota', 1997, 'Minnesota', 'http://www.wild.com/', '37', 'TRUE', 'Xcel Energy Center', 'St. Paul', 5098, 'America/Chicago', -5, 'CDT', '16', 'Central', 'CEN', 'C', '5', 'Western', '37', 'Wild');

INSERT INTO dim_team (team_id, name, abbreviation, team_name, location_name, first_year_of_play, short_name, official_site_url, franchise_id, active, venue_name, venue_city, venue_id, venue_time_zone_id, venue_time_zone_offset, venue_time_zone_tz, division_id, division_name, division_name_short, division_abbreviation, conference_id, conference_name, franchise_franchise_id, franchise_team_name) 
VALUES ('52', 'Winnipeg Jets', 'WPG', 'Jets', 'Winnipeg', 2011, 'Winnipeg', 'http://winnipegjets.com/', '35', 'TRUE', 'Canada Life Centre', 'Winnipeg', 5058, 'America/Winnipeg', -5, 'CDT', '16', 'Central', 'CEN', 'C', '5', 'Western', '35', 'Jets');

INSERT INTO dim_team (team_id, name, abbreviation, team_name, location_name, first_year_of_play, short_name, official_site_url, franchise_id, active, venue_name, venue_city, venue_id, venue_time_zone_id, venue_time_zone_offset, venue_time_zone_tz, division_id, division_name, division_name_short, division_abbreviation, conference_id, conference_name, franchise_franchise_id, franchise_team_name) 
VALUES ('53', 'Arizona Coyotes', 'ARI', 'Coyotes', 'Arizona', 1979, 'Arizona', 'http://www.arizonacoyotes.com/', '28', 'TRUE', 'Mullett Arena', 'Tempe', NULL, 'America/Phoenix', -7, 'MST', '16', 'Central', 'CEN', 'C', '5', 'Western', '28', 'Coyotes');

INSERT INTO dim_team (team_id, name, abbreviation, team_name, location_name, first_year_of_play, short_name, official_site_url, franchise_id, active, venue_name, venue_city, venue_id, venue_time_zone_id, venue_time_zone_offset, venue_time_zone_tz, division_id, division_name, division_name_short, division_abbreviation, conference_id, conference_name, franchise_franchise_id, franchise_team_name) 
VALUES ('54', 'Vegas Golden Knights', 'VGK', 'Golden Knights', 'Vegas', 2016, 'Vegas', 'http://www.vegasgoldenknights.com/', '38', 'TRUE', 'T-Mobile Arena', 'Las Vegas', 5178, 'America/Los_Angeles', -7, 'PDT', '15', 'Pacific', 'PAC', 'P', '5', 'Western', '38', 'Golden Knights');

INSERT INTO dim_team (team_id, name, abbreviation, team_name, location_name, first_year_of_play, short_name, official_site_url, franchise_id, active, venue_name, venue_city, venue_id, venue_time_zone_id, venue_time_zone_offset, venue_time_zone_tz, division_id, division_name, division_name_short, division_abbreviation, conference_id, conference_name, franchise_franchise_id, franchise_team_name) 
VALUES ('55', 'Seattle Kraken', 'SEA', 'Kraken', 'Seattle', 2021, 'Seattle', 'https://www.nhl.com/seattle', '39', 'TRUE', 'Climate Pledge Arena', 'Seattle', NULL, 'America/Los_Angeles', -7, 'PDT', '15', 'Pacific', 'PAC', 'P', '5', 'Western', '39', 'Kraken');

